# =============================================================================
# scripts/slurm/uci-hpc3/_config.sh
# =============================================================================
# Cluster-wide and personal settings sourced by every UCI HPC3 .sub script.
#
# Override any of these at submit time:
#
#     CORDIS_ACCOUNT=other_lab sbatch scripts/slurm/uci-hpc3/exp_sinr_cdf.sub
#
# Generated by scripts/regenerate_experiment_scripts.py.
# =============================================================================

# Cluster settings.
export CORDIS_ACCOUNT="${CORDIS_ACCOUNT:-swindle_lab}"
export CORDIS_PARTITION="${CORDIS_PARTITION:-standard}"

# Personal settings.
export CORDIS_MAIL_USER="${CORDIS_MAIL_USER:-mzafarid@uci.edu}"
export CORDIS_MAIL_TYPE="${CORDIS_MAIL_TYPE:-END,FAIL}"

# Environment.
export CORDIS_REPO_DIR="${CORDIS_REPO_DIR:-/pub/$USER/CORDIS}"
export CORDIS_PYTHON_MODULE="${CORDIS_PYTHON_MODULE:-python/3.14.3}"
export CORDIS_VENV="${CORDIS_VENV:-cordis_venv}"
