#!/usr/bin/env python3
"""
Build the four playground notebooks from in-script cell definitions.

This script is a build-time tool used to produce
``notebooks/playground_<kind>.ipynb``.  It is kept under
``notebooks/`` so the notebooks live next to their source-of-truth.

Run::

    python3 notebooks/_build_playgrounds.py

Re-run after editing this script to regenerate all four notebooks.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import List

HERE = Path(__file__).resolve().parent       # notebooks/


# ─────────────────────────────────────────────────────────────────────
#  Notebook-cell builders
# ─────────────────────────────────────────────────────────────────────

def code(*lines: str) -> dict:
    """Build a code cell from a list of source lines (no trailing \\n needed)."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": "\n".join(lines),
    }


def md(*lines: str) -> dict:
    """Build a markdown cell."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": "\n".join(lines),
    }


def notebook(cells: List[dict]) -> dict:
    """Wrap cells in a minimal Jupyter nbformat 4.5 document."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language":     "python",
                "name":         "python3",
            },
            "language_info": {
                "name":      "python",
                "version":   "3.x",
                "mimetype":  "text/x-python",
                "file_extension":   ".py",
            },
        },
        "nbformat":       4,
        "nbformat_minor": 5,
    }


# ─────────────────────────────────────────────────────────────────────
#  Shared cell snippets — used across all four notebooks
# ─────────────────────────────────────────────────────────────────────

INTRO_SETUP = code(
    "# Stage 12: shared setup — make `cordis` importable when this notebook",
    "# is launched from notebooks/, then apply the IEEE paper rcParams.",
    "import sys, logging",
    "from pathlib import Path",
    "from _playground_helpers import (",
    "    setup_paper_style, load_latest_result, load_run, load_result, summarize,",
    ")",
    "",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "",
    "# Set use_latex=False if pdflatex isn't on PATH (e.g. on a compute node).",
    "setup_paper_style(use_latex=True)",
    "",
    "logging.basicConfig(level=logging.WARNING, format='%(levelname)-7s %(message)s')",
)


GENERIC_FIGSIZE_CELL = code(
    "# Figsize variants — `figsize` returns (w, h) in inches for matplotlib.",
    "# width: 'single' (one column), 'double' (two-column), 'third' (3-up panel).",
    "# aspect: w/h ratio.  Tweak both to fit your paper layout.",
    "from cordis.plotting import figsize",
    "",
    "for width in ('single', 'double', 'third'):",
    "    w, h = figsize(width=width, aspect=3/2)",
    "    print(f'{width:>6}: ({w:.2f}, {h:.2f}) inches')",
    "",
    "# Example: tight three-up panel for a paper sub-figure",
    "# fig, axes = plt.subplots(1, 3, figsize=figsize(width='double', aspect=3.5/1.5))",
)


GENERIC_SAVE_CELL = code(
    "# Save with provenance metadata (Git SHA, creation date, etc. — embedded",
    "# into the PDF's metadata, prepended as comments in the .pgf).",
    "from cordis.plotting import save_figure",
    "",
    "# Adjust EXPERIMENT and metric labels to match the figure above.",
    "out = save_figure(",
    "    fig,",
    "    base_path=f'../figures/playground/{EXPERIMENT}_demo',",
    "    formats=('pdf', 'png'),       # add 'pgf' on systems with LaTeX",
    "    metadata={'Experiment': EXPERIMENT, 'Notebook': 'playground'},",
    ")",
    "for p in out:",
    "    print('wrote', p)",
)


# Stage 21 — setup cell for the array playgrounds.  Pulls in the
# array-specific helpers (load_aggregated_array_result, array_summary,
# per_task_summary, print_per_task_summary) instead of the single-run
# load_*  helpers.
INTRO_SETUP_ARRAY = code(
    "# Shared setup: make `cordis` importable from notebooks/ + IEEE rcParams.",
    "import sys, logging",
    "from pathlib import Path",
    "from _playground_helpers import (",
    "    setup_paper_style,",
    "    load_aggregated_array_result, array_summary,",
    "    print_per_task_summary, per_task_summary,",
    ")",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "",
    "# Set use_latex=False if pdflatex isn't on PATH on this machine.",
    "setup_paper_style(use_latex=True)",
    "logging.basicConfig(level=logging.WARNING, format='%(levelname)-7s %(message)s')",
)


# ─────────────────────────────────────────────────────────────────────
#  CDF notebook (sinr_cdf, scnr_cdf)
# ─────────────────────────────────────────────────────────────────────

def build_cdf_notebook() -> dict:
    cells = [
        md(
            "# CDF Playground",
            "",
            "Interactive exploration of empirical-CDF figures (`sinr_cdf`, `scnr_cdf`).",
            "",
            "**Workflow.**  Run a CDF experiment first — e.g. `make sinr_cdf` — to",
            "populate `results/exp_sinr_cdf/<ts>/`.  Set `exp_name` below to the",
            "metric family (`'sinr'` or `'scnr'`) and iterate on the cells.",
            "Switching between SINR and SCNR is one edit; all subsequent cells",
            "derive their experiment folder, metric names, and titles from",
            "`exp_name`.",
            "",
            "**Compatible experiments:** `sinr_cdf`, `scnr_cdf`",
            "(both use `kind == 'single'` and the `plot_cdf` function).",
        ),
        INTRO_SETUP,
        code(
            "# ── The one knob: which metric family to load ──",
            "exp_name = 'sinr'              # 'sinr' or 'scnr'",
            "",
            "# Optional: load a specific run directory instead of the latest.",
            "# Set to a path like 'results/exp_sinr_cdf/20260520_113500'",
            "# (relative to the repo root) to re-render an older comparison.",
            "EXP_DIR = None",
            "",
            "# Derived names — change `exp_name` above and these update automatically.",
            "EXPERIMENT     = f'{exp_name}_cdf'        # 'sinr_cdf' / 'scnr_cdf'",
            "METRIC_MIN     = f'min_{exp_name}_db'     # 'min_sinr_db' / 'min_scnr_db'",
            "METRIC_MEAN    = f'mean_{exp_name}_db'    # 'mean_sinr_db' / 'mean_scnr_db'",
            "METRIC_DISPLAY = exp_name.upper()         # 'SINR' / 'SCNR'  (for titles)",
            "",
            "result = load_result(EXPERIMENT, EXP_DIR)",
            "assert result.kind == 'single', (",
            "    f'This notebook is for CDF (kind=\"single\") experiments; '",
            "    f'got kind={result.kind}.  Use playground_sweep / _trace / _table.'",
            ")",
            "summarize(result)",
        ),
        md("## 1. Quick CDF — all algorithms"),
        code(
            "from cordis.plotting import plot_cdf, figsize",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax)",
            "ax.set_title(f'{EXPERIMENT}: min-{METRIC_DISPLAY} CDF')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        md(
            "## 2. Filter algorithms via `only=`",
            "",
            "`plot_cdf` accepts an `only=` list of algorithm display names — anything",
            "not in the list is silently skipped.  Colors/markers stay consistent with",
            "`ALGORITHM_STYLE` even when you drop algorithms.",
        ),
        code(
            "# Pick just the algorithms you want — easy A/B comparison.",
            "PICK = ['CORDIS-Split', 'CORDIS-ADMM', 'Centralized']",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "ax.set_title(f'{EXPERIMENT}: CORDIS vs. Centralized')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        md(
            "## 3. Alternate metrics — min vs. mean",
            "",
            "The SimResult typically carries several metrics per run.  For the",
            "currently-selected family (SINR or SCNR), the canonical pair is",
            "`min_<family>_db` and `mean_<family>_db`.  Comparing the two side-",
            "by-side shows how algorithm rankings shift between the worst-user",
            "view and the average view.",
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=figsize(width='double', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=axes[0], only=PICK)",
            "axes[0].set_title(f'Worst-user {METRIC_DISPLAY}')",
            "axes[0].set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plot_cdf(result.sim_result, metric=METRIC_MEAN, ax=axes[1], only=PICK)",
            "axes[1].set_title(f'Average-user {METRIC_DISPLAY}')",
            "axes[1].set_xlabel(f'mean-{METRIC_DISPLAY} [dB]')",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md(
            "## 4. Per-algorithm style override",
            "",
            "`ALGORITHM_STYLE` is a dict; monkey-patch entries for one-off tweaks",
            "without committing changes to `cordis/plotting/style.py`.",
        ),
        code(
            "from cordis.plotting.style import ALGORITHM_STYLE",
            "import copy",
            "",
            "# Snapshot original so cell is re-runnable.",
            "_orig = copy.deepcopy(ALGORITHM_STYLE)",
            "",
            "# Bump CORDIS-Split to a heavier line, switch its color.",
            "if 'CORDIS-Split' in ALGORITHM_STYLE:",
            "    ALGORITHM_STYLE['CORDIS-Split']['linewidth'] = 2.5",
            "    ALGORITHM_STYLE['CORDIS-Split']['color']     = '#d62728'",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "ax.set_title('Style override demo (red, thicker Split)')",
            "plt.show()",
            "",
            "# Restore the original style so subsequent cells aren't affected.",
            "ALGORITHM_STYLE.clear(); ALGORITHM_STYLE.update(_orig)",
        ),
        md(
            "## 5. Tail behavior — log x-axis",
            "",
            "Useful when the interesting story is in the outage region",
            "(e.g. 5th-percentile SINR).",
        ),
        code(
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "# Mark the 5%/50%/95% lines",
            "for q in (0.05, 0.5, 0.95):",
            "    ax.axhline(q, color='lightgray', linestyle=':', linewidth=0.8, zorder=0)",
            "ax.set_ylim(0, 1)",
            "plt.show()",
        ),
        md("## 6. Figsize variants"),
        GENERIC_FIGSIZE_CELL,
        md("## 7. Save with provenance metadata"),
        GENERIC_SAVE_CELL,
        md(
            "## 8. Multi-run overlay",
            "",
            "Compare two runs of the same experiment — e.g. before vs. after",
            "tuning a parameter — by loading both and overlaying their curves.",
            "",
            "Set `RUN_A` / `RUN_B` to two specific run paths to enable this cell;",
            "remove them or set to `None` to skip.",
        ),
        code(
            "RUN_A = None    # e.g. 'results/exp_sinr_cdf/2026-05-18_12-00-00'",
            "RUN_B = None    # e.g. 'results/exp_sinr_cdf/2026-05-19_15-30-00'",
            "",
            "if RUN_A and RUN_B:",
            "    res_a = load_run(RUN_A)",
            "    res_b = load_run(RUN_B)",
            "    fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "    # plot_cdf doesn't accept linestyle/label_suffix kwargs, so we",
            "    # post-process the Line2D objects to differentiate the two runs.",
            "    n_before_a = len(ax.lines)",
            "    plot_cdf(res_a.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "    n_before_b = len(ax.lines)",
            "    for ln in ax.lines[n_before_a:n_before_b]:",
            "        ln.set_linestyle('--')",
            "        ln.set_label(ln.get_label() + ' (A)')",
            "    plot_cdf(res_b.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "    for ln in ax.lines[n_before_b:]:",
            "        ln.set_label(ln.get_label() + ' (B)')",
            "    ax.legend(loc='best')        # refresh legend after relabeling",
            "    plt.show()",
            "else:",
            "    print('Set RUN_A and RUN_B above to compare two runs.')",
        ),
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Sweep notebook (snr_sweep, gamma_sweep, kappa_sweep, ...)
# ─────────────────────────────────────────────────────────────────────

def build_sweep_notebook() -> dict:
    cells = [
        md(
            "# Sweep Playground",
            "",
            "Interactive exploration of sweep figures — single-variable parameter",
            "sweeps that produce a metric-vs-axis curve per algorithm.",
            "",
            "**Compatible experiments:** `snr_sweep`, `gamma_sweep`, `kappa_sweep`,",
            "`clutter_cnr_sweep`, `n_ue_sweep`, `n_ap_sweep`, `antennas_sweep`",
            "(all use `kind == 'sweep'` and the `plot_sweep` function).",
            "",
            "**The one knob.**  Set `exp_name` (e.g. `'snr'`, `'kappa'`, `'gamma'`)",
            "and the experiment folder is derived as `f'{exp_name}_sweep'`.",
            "Switching between, say, `snr_sweep` and `kappa_sweep` results is one",
            "edit — axis labels come from `result.sweep_axis.display` so they update",
            "automatically.",
        ),
        INTRO_SETUP,
        code(
            "# ── The one knob: which sweep parameter ──",
            "exp_name = 'snr'              # snr / gamma / kappa / clutter_cnr",
            "                              # / n_ue / n_ap / antennas",
            "",
            "# Optional: load a specific run directory instead of the latest.",
            "# Set to a path like 'results/exp_snr_sweep/20260520_113500'",
            "# (relative to the repo root) to re-render an older comparison.",
            "EXP_DIR = None",
            "",
            "EXPERIMENT = f'{exp_name}_sweep'",
            "",
            "result = load_result(EXPERIMENT, EXP_DIR)",
            "assert result.kind == 'sweep', (",
            "    f'This notebook is for sweep experiments; got kind={result.kind}.'",
            ")",
            "summarize(result)",
        ),
        md(
            "## 1. Quick sweep plot — one metric, all algorithms",
            "",
            "`plot_sweep` takes the keyed-by-x results dict (its x-axis comes",
            "from the dict's keys, not from `sweep_axis`).  The `sweep_axis`",
            "metadata is used for human-readable axis labels — set them yourself",
            "via `ax.set_xlabel(result.sweep_axis.display)` etc.",
        ),
        code(
            "from cordis.plotting import plot_sweep, figsize",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax)",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('min-SINR [dB]')",
            "ax.set_title(f'{EXPERIMENT}: min-SINR vs. {result.sweep_axis.display}')",
            "plt.show()",
        ),
        md(
            "## 2. Side-by-side: SINR + SCNR",
            "",
            "Most paper figures pair a communication metric with a sensing metric.",
            "Build the two-panel layout inline — no helper needed.",
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=figsize(width='double', aspect=2.5/1.5))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=axes[0])",
            "axes[0].set_xlabel(result.sweep_axis.display)",
            "axes[0].set_ylabel('min-SINR [dB]')",
            "axes[0].set_title('min-SINR [dB]')",
            "plot_sweep(result.sweep_results, metric='mean_scnr_db', ax=axes[1])",
            "axes[1].set_xlabel(result.sweep_axis.display)",
            "axes[1].set_ylabel('mean-SCNR [dB]')",
            "axes[1].set_title('mean-SCNR [dB]')",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md(
            "## 3. Algorithm filter — focus on CORDIS vs. Centralized",
            "",
            "`plot_sweep` honors the same `only=` keyword as `plot_cdf`.",
        ),
        code(
            "PICK = ['CORDIS-Split', 'CORDIS-ADMM', 'Centralized']",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('min-SINR [dB]')",
            "plt.show()",
        ),
        md(
            "## 4. Log-y for SCNR sweeps",
            "",
            "Sensing metrics often span orders of magnitude across the sweep range.",
        ),
        code(
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='mean_scnr_db', ax=ax, only=PICK)",
            "ax.set_yscale('log')",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('mean SCNR (log scale)')",
            "plt.show()",
        ),
        md(
            "## 5. Annotate the operating point",
            "",
            "If your paper highlights a specific axis value (e.g. SNR=10 dB), draw",
            "a vertical line + label at that point.",
        ),
        code(
            "x_marker = 10.0                # adjust to your sweep's axis units",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "ax.set_xlabel(result.sweep_axis.display)",
            "if min(result.sweep_axis.values) <= x_marker <= max(result.sweep_axis.values):",
            "    ax.axvline(x_marker, color='gray', linestyle=':', linewidth=1)",
            "    ax.annotate(f'  operating point ({x_marker})',",
            "                xy=(x_marker, ax.get_ylim()[1]),",
            "                xytext=(5, -10), textcoords='offset points',",
            "                fontsize=8, color='gray')",
            "plt.show()",
        ),
        md("## 6. Figsize variants"),
        GENERIC_FIGSIZE_CELL,
        md("## 7. Save with provenance metadata"),
        GENERIC_SAVE_CELL,
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Trace notebook (convergence_trace)
# ─────────────────────────────────────────────────────────────────────

def build_trace_notebook() -> dict:
    cells = [
        md(
            "# ADMM Convergence Trace Playground",
            "",
            "Interactive exploration of ADMM convergence diagnostics —",
            "primal/dual residuals and slack history across iterations.",
            "",
            "**Compatible experiments:** `convergence_trace`",
            "(uses `kind == 'trace'` and the `plot_admm_convergence` function).",
        ),
        INTRO_SETUP,
        code(
            "EXPERIMENT = 'convergence_trace'",
            "",
            "# Optional: load a specific run directory instead of the latest.",
            "# Set to a path like 'results/exp_convergence_trace/20260520_113500'",
            "# (relative to the repo root) to re-render an older trace.",
            "EXP_DIR = None",
            "",
            "result = load_result(EXPERIMENT, EXP_DIR)",
            "assert result.kind == 'trace'",
            "summarize(result)",
            "",
            "# `best_iter` may be 0 (no iterations run) or None (loaded from a",
            "# pre-Stage-18 result that didn't store it).  Cells below handle",
            "# both gracefully.",
            "best_iter = getattr(result.admm_result, 'best_iter', None)",
            "print(f'Best iter: {best_iter}')",
            "print(f'Total iters: {len(result.admm_result.primal_res_history)}')",
        ),
        md("## 1. Standard convergence plot"),
        code(
            "from cordis.plotting import plot_admm_convergence, figsize",
            "",
            "# plot_admm_convergence produces a TWO-panel figure (residuals + slack).",
            "# Pre-create both axes and pass them as the `axes=(ax_top, ax_bot)` tuple,",
            "# or call without `axes` to let the function build its own figure.",
            "fig, (ax_res, ax_slack) = plt.subplots(",
            "    1, 2, figsize=figsize(width='double', aspect=2.5/1.5),",
            ")",
            "plot_admm_convergence(result.admm_result, axes=(ax_res, ax_slack))",
            "fig.suptitle('ADMM convergence (primal/dual residuals + slack history)')",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md(
            "## 2. Primal / dual on twin axes",
            "",
            "When primal and dual residuals have very different scales, a single",
            "log-y axis still works but a twin-axes layout makes both visible.",
            "If `best_iter` is set (Stage 18+ trace results), a vertical guide",
            "marks it.",
        ),
        code(
            "admm = result.admm_result",
            "iters = np.arange(1, len(admm.primal_res_history) + 1)",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "ln1 = ax.semilogy(iters, admm.primal_res_history, label='primal', color='C0')",
            "ax.set_xlabel('ADMM iteration')",
            "ax.set_ylabel('primal residual', color='C0')",
            "ax.tick_params(axis='y', labelcolor='C0')",
            "",
            "ax2 = ax.twinx()",
            "ln2 = ax2.semilogy(iters, admm.dual_res_history, label='dual', color='C3', linestyle='--')",
            "ax2.set_ylabel('dual residual', color='C3')",
            "ax2.tick_params(axis='y', labelcolor='C3')",
            "",
            "# Guard against best_iter being None (legacy loaded result) or 0",
            "# (solver returned before recording any iteration).",
            "_bi = getattr(admm, 'best_iter', None)",
            "if _bi:",
            "    ax.axvline(_bi, color='gray', linestyle=':', linewidth=0.8)",
            "    ax.set_title(f'Twin-axes residuals (best iter = {_bi})')",
            "else:",
            "    ax.set_title('Twin-axes residuals (best_iter unavailable)')",
            "plt.show()",
        ),
        md(
            "## 3. Slack history overlay",
            "",
            "When ALM/MoM is used, the slack penalty rises as it discovers QoS",
            "violations.  Overlaying its history on top of residuals shows when",
            "the algorithm 'gives up' enforcing a tight constraint.",
        ),
        code(
            "if hasattr(admm, 'slack_history') and admm.slack_history is not None \\",
            "        and len(admm.slack_history):",
            "    fig, axes = plt.subplots(2, 1, figsize=figsize(width='single', aspect=3/2.5),",
            "                              sharex=True)",
            "    axes[0].semilogy(iters, admm.primal_res_history, label='primal', color='C0')",
            "    axes[0].semilogy(iters, admm.dual_res_history,   label='dual',   color='C3')",
            "    axes[0].legend()",
            "    axes[0].set_ylabel('residual')",
            "    axes[1].plot(iters, admm.slack_history, color='C2')",
            "    axes[1].set_ylabel('slack')",
            "    axes[1].set_xlabel('ADMM iteration')",
            "    plt.tight_layout()",
            "    plt.show()",
            "else:",
            "    print('No slack_history in this trace.')",
        ),
        md(
            "## 4. Per-user convergence diagnostic",
            "",
            "Specifically designed to test the *warm-start hypothesis*: if",
            "CORDIS-ADMM warm-starts from a poor initial PSR (e.g. equal",
            "50/50 instead of Split-optimal), the min-SINR user is often",
            "frozen near the warm-start while other users move toward their",
            "γ target.  This shows up as:",
            "",
            "* `best_iter` small (≤ a few) → algorithm's best W is essentially the warm-start",
            "* exactly one user has near-zero SINR std across iterations *and* the largest slack",
            "* that user's final SINR is far below γ",
            "",
            "If the pattern matches, the fix is to change the warm-start.",
            "If it doesn't, the diagnosis needs to continue.",
        ),
        code(
            "# ── Convergence summary ─────────────────────────────────────",
            "# getattr() guards every attribute so legacy traces (saved",
            "# before the per-user diagnostic fields were persisted)",
            "# render as 'n/a' rather than raising AttributeError.",
            "best_iter     = getattr(admm, 'best_iter', None)",
            "n_iters_run   = getattr(admm, 'n_admm_iters', None)",
            "converged     = getattr(admm, 'converged', None)",
            "feasible      = getattr(admm, 'feasible', None)",
            "inner_fail    = getattr(admm, 'inner_failures', None)",
            "print(f'best_iter   = {best_iter}')",
            "print(f'n_iters_run = {n_iters_run if n_iters_run is not None else \"n/a\"}')",
            "print(f'converged   = {converged if converged is not None else \"n/a\"}')",
            "print(f'feasible    = {feasible}   (any inner solve succeeded somewhere)')",
            "print(f'inner_fail  = {inner_fail if inner_fail is not None else \"n/a\"}'",
            "      f'   (total subproblem failures across all iters)')",
            "print()",
            "",
            "# ── Per-user trajectories ───────────────────────────────────",
            "# sinr_history: list/array of per-user SINR vectors, one per",
            "# outer iter, shape [n_iter, n_ue].  None on legacy traces.",
            "sinr_hist_raw  = getattr(admm, 'sinr_history', None)",
            "slack_hist_raw = getattr(admm, 'slack_history', None)",
            "",
            "def _has_data(x):",
            "    if x is None: return False",
            "    try:",
            "        return len(x) > 0",
            "    except TypeError:",
            "        return bool(np.asarray(x).size)",
            "",
            "if not _has_data(sinr_hist_raw):",
            "    print('⚠  No sinr_history in this trace file.')",
            "    print('   This trace was likely saved BEFORE Stage-18-diag-v2 extended')",
            "    print('   the per-iter persistence.  Re-run the experiment to capture:')",
            "    print('      bash scripts/exp_convergence_trace.sh')",
            "    print('   Then Restart-Run-All this notebook.')",
            "else:",
            "    sinr_db_hist = np.stack([",
            "        10 * np.log10(np.maximum(np.asarray(s, dtype=float), 1e-30))",
            "        for s in sinr_hist_raw",
            "    ])                                       # [n_iter, n_ue]",
            "    slack_hist = np.stack([np.asarray(s, dtype=float)",
            "                           for s in slack_hist_raw])",
            "    n_iter, n_ue = sinr_db_hist.shape",
            "    print(f'{\"user\":>4} | {\"init dB\":>9} | {\"final dB\":>9} |'",
            "          f' {\"std dB\":>7} | {\"max slack\":>10}')",
            "    print('-' * 56)",
            "    for u in range(n_ue):",
            "        init  = sinr_db_hist[0, u]",
            "        final = sinr_db_hist[-1, u]",
            "        std   = sinr_db_hist[:, u].std()",
            "        smax  = slack_hist[:, u].max()",
            "        flag  = '  ← stuck?' if std < 0.5 else ''",
            "        print(f'{u:>4} | {init:+9.1f} | {final:+9.1f} |'",
            "              f' {std:>7.2f} | {smax:>10.2e}{flag}')",
            "    print()",
            "    print(f'min over users (final iter):     {sinr_db_hist[-1].min():+.2f} dB')",
            "    if best_iter:",
            "        bi_idx = max(int(best_iter) - 1, 0)",
            "        print(f'min over users (best iter {best_iter}):  '",
            "              f'{sinr_db_hist[bi_idx].min():+.2f} dB')",
        ),
        md(
            "### 4b. Per-user SINR trajectories (visual)",
            "",
            "Each line is one user.  A line that stays flat across iterations",
            "is the stuck user — they didn't budge from the warm-start.",
            "Lines that climb toward `γ` are the users the algorithm is",
            "successfully serving.",
        ),
        code(
            "if _has_data(sinr_hist_raw):",
            "    fig, (ax_sinr, ax_slack) = plt.subplots(",
            "        1, 2, figsize=figsize(width='double', aspect=2.5/1.5),",
            "    )",
            "    iters_axis = np.arange(1, n_iter + 1)",
            "    for u in range(n_ue):",
            "        ax_sinr.plot(iters_axis, sinr_db_hist[:, u],",
            "                     label=f'u={u}', alpha=0.85)",
            "        ax_slack.semilogy(iters_axis,",
            "                          np.maximum(slack_hist[:, u], 1e-30),",
            "                          label=f'u={u}', alpha=0.85)",
            "    # Mark γ if available in metadata.  run_convergence_trace",
            "    # stores per-user γ vector under 'gamma_u_db_uniform' (the",
            "    # _uniform suffix is added by the ExperimentResult metadata",
            "    # builder for ndarray params).  Fall back to the scalar key",
            "    # if a future code path uses one.",
            "    gamma_db = (result.metadata.get('gamma_u_db_uniform')",
            "                or result.metadata.get('gamma_db'))",
            "    if gamma_db is not None:",
            "        try:",
            "            ax_sinr.axhline(float(gamma_db), color='k', linestyle='--',",
            "                            linewidth=0.8,",
            "                            label=rf'$\\gamma$ = {float(gamma_db):.1f} dB')",
            "        except (TypeError, ValueError):",
            "            pass",
            "    _bi = getattr(admm, 'best_iter', None)",
            "    if _bi:",
            "        for ax in (ax_sinr, ax_slack):",
            "            ax.axvline(_bi, color='gray', linestyle=':',",
            "                       linewidth=0.8, label=f'best iter = {_bi}')",
            "    ax_sinr.set_xlabel('ADMM iteration')",
            "    ax_sinr.set_ylabel('per-user SINR [dB]')",
            "    ax_sinr.set_title('Per-user SINR trajectories')",
            "    ax_sinr.legend(fontsize=7, ncol=2, loc='best')",
            "    ax_sinr.grid(True, alpha=0.3)",
            "    ax_slack.set_xlabel('ADMM iteration')",
            "    ax_slack.set_ylabel(r'per-user slack $\\varepsilon_u$')",
            "    ax_slack.set_title('Per-user slack trajectories')",
            "    ax_slack.legend(fontsize=7, ncol=2, loc='best')",
            "    ax_slack.grid(True, alpha=0.3)",
            "    plt.tight_layout()",
            "    plt.show()",
            "else:",
            "    print('Skipping plot — no per-iteration history available.')",
            "    print('(See message above for how to capture it.)')",
        ),
        md(
            "## 5. Convergence-rate fit (rough)",
            "",
            "Fit a geometric rate to the primal residual tail (last ~30% of iters)",
            "to quantify how fast ADMM is converging.",
        ),
        code(
            "tail_frac = 0.3",
            "n         = len(admm.primal_res_history)",
            "tail_start = max(1, int(n * (1 - tail_frac)))",
            "tail_iters = iters[tail_start:]",
            "tail_res   = admm.primal_res_history[tail_start:]",
            "",
            "# log y = a + b * iter  →  y = exp(a) * exp(b)^iter",
            "if np.all(np.asarray(tail_res) > 0):",
            "    coeffs = np.polyfit(tail_iters, np.log(tail_res), 1)",
            "    rate   = np.exp(coeffs[0])     # geometric ratio per iter",
            "    print(f'Tail geometric rate: r ≈ {rate:.4f}  (per iter)')",
            "    if rate < 1:",
            "        print(f'                     1/(1-r) ≈ {1/(1-rate):.1f}  iters to settle')",
            "    else:",
            "        print(f'                     rate ≥ 1 — residual is GROWING, not shrinking')",
            "else:",
            "    print('Tail contains zeros/negatives; skipping rate fit.')",
        ),
        md("## 6. Figsize variants"),
        GENERIC_FIGSIZE_CELL,
        md("## 7. Save with provenance metadata"),
        GENERIC_SAVE_CELL,
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Table notebook (fronthaul_table)
# ─────────────────────────────────────────────────────────────────────

def build_table_notebook() -> dict:
    cells = [
        md(
            "# Table Playground",
            "",
            "Interactive exploration of tabular results — render as Markdown,",
            "LaTeX (booktabs), or as a bar chart for visual comparison.",
            "",
            "**Compatible experiments:** `fronthaul_table`",
            "(uses `kind == 'table'`).",
            "",
            "Note: `result.table_data` is a `Dict[algorithm_name, Dict[field, value]]`",
            "structure — NOT a `SimResult`.  The `cordis.plotting.bar_chart` and",
            "`to_*_table` functions expect a `SimResult`, so this notebook builds",
            "tables and charts from `result.table_data` directly (matching what",
            "`scripts/plot_fronthaul_table.py` does).",
        ),
        INTRO_SETUP,
        code(
            "EXPERIMENT = 'fronthaul_table'",
            "",
            "# Optional: load a specific run directory instead of the latest.",
            "# Set to a path like 'results/exp_fronthaul_table/20260520_113500'",
            "# (relative to the repo root) to re-render an older table.",
            "EXP_DIR = None",
            "",
            "result = load_result(EXPERIMENT, EXP_DIR)",
            "assert result.kind == 'table'",
            "summarize(result)",
            "print()",
            "print('Algorithms in table:', list(result.table_data.keys()))",
            "first_algo = next(iter(result.table_data))",
            "print(f'Fields per algorithm: {list(result.table_data[first_algo].keys())}')",
        ),
        md("## 1. Markdown render (good for previews + GitHub READMEs)"),
        code(
            "# Mirrors what scripts/plot_fronthaul_table.py emits.",
            "# real_scalars is PER COORDINATION ROUND (apples-to-apples across",
            "# algorithms).  iterations holds the per-solve multiplier",
            "# (1 for Centralized/Split, T_ADMM for ADMM).",
            "lines = [",
            "    '| Algorithm | Data shared | Size | Real scalars / round | Iterations | Total / solve | Scalable |',",
            "    '|---|---|---|---|---|---|---|',",
            "]",
            "for algo, row in result.table_data.items():",
            "    rs = row.get('real_scalars')",
            "    it = row.get('iterations')",
            "    rs_str = '—' if rs is None else (",
            "        f'{rs:.1f}' if isinstance(rs, float) else f'{rs:d}'",
            "    )",
            "    it_str = '—' if it is None else (",
            "        f'{it:.1f}' if isinstance(it, float) and not float(it).is_integer()",
            "        else f'{int(it):d}'",
            "    )",
            "    tot_str = '—' if (rs is None or it is None) else (",
            "        f'{float(rs) * float(it):.0f}'",
            "    )",
            "    lines.append(",
            "        f\"| {algo} | {row['data_to_share']} | {row['size']} | \"",
            "        f\"{rs_str} | {it_str} | {tot_str} | \"",
            "        f\"{'✓' if row['scalable'] else '✗'} |\"",
            "    )",
            "print('\\n'.join(lines))",
        ),
        md(
            "## 2. LaTeX render for the paper",
            "",
            "Uses `booktabs` style.  Copy-paste the output into your paper's `.tex`",
            "(or use `\\input{...}` from a saved `.tex` file).",
        ),
        code(
            "tex_lines = [",
            "    r'\\begin{table}[t]',",
            "    r'\\centering',",
            "    r'\\caption{Per-AP fronthaul coordination overhead.}',",
            "    r'\\label{tab:fronthaul}',",
            "    r'\\begin{tabular}{lcccc}',",
            "    r'\\toprule',",
            "    r'Algorithm & Data shared & Size & Real / iter & Scalable \\\\',",
            "    r'\\midrule',",
            "]",
            "for algo, row in result.table_data.items():",
            "    rs = row.get('real_scalars')",
            "    rs_str = '--' if rs is None else (",
            "        f'{rs:.1f}' if isinstance(rs, float) else f'{rs:d}'",
            "    )",
            "    tex_lines.append(",
            "        f\"{algo} & {row['data_to_share']} & {row['size']} & \"",
            "        f\"{rs_str} & \"",
            "        + (r'$\\checkmark$' if row['scalable'] else r'$\\times$')",
            "        + r' \\\\'",
            "    )",
            "tex_lines += [r'\\bottomrule', r'\\end{tabular}', r'\\end{table}']",
            "tex = '\\n'.join(tex_lines)",
            "print(tex)",
            "",
            "# Save it for \\input{} from your paper.",
            "out = Path('../figures/playground/fronthaul_table.tex')",
            "out.parent.mkdir(parents=True, exist_ok=True)",
            "out.write_text(tex)",
            "print(f'wrote {out}')",
        ),
        md(
            "## 3. Bar chart — per-round fronthaul cost",
            "",
            "All algorithms reported per coordination round (apples-to-apples).",
            "Centralized + Split run 1 round per coherence block; CORDIS-ADMM",
            "runs T_ADMM rounds — shown in the `iterations` column above.",
            "",
            "When numbers span orders of magnitude (e.g. fronthaul scalars from",
            "a few to a few hundred), a log-y bar chart often communicates the",
            "gap better than the numeric table alone.  Built from",
            "`result.table_data` directly with raw matplotlib (since",
            "`cordis.plotting.bar_chart` expects a SimResult).",
        ),
        code(
            "from cordis.plotting import figsize",
            "",
            "# Pull the per-round count for plotting, skip rows with None.",
            "algs   = []",
            "values = []",
            "for algo, row in result.table_data.items():",
            "    rs = row.get('real_scalars')",
            "    if rs is None:",
            "        continue",
            "    algs.append(algo)",
            "    values.append(float(rs))",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "bars = ax.bar(range(len(algs)), values, color='C0', edgecolor='black')",
            "ax.set_yscale('log')",
            "ax.set_xticks(range(len(algs)))",
            "ax.set_xticklabels(algs, rotation=20, ha='right')",
            "ax.set_ylabel('real scalars per AP per coordination round')",
            "ax.set_title('Per-round fronthaul cost (log scale)')",
            "ax.grid(True, axis='y', alpha=0.3)",
            "",
            "# Annotate each bar with the count for clarity.",
            "for rect, v in zip(bars, values):",
            "    ax.annotate(f'{v:.0f}', xy=(rect.get_x() + rect.get_width()/2,",
            "                                rect.get_height()),",
            "                xytext=(0, 3), textcoords='offset points',",
            "                ha='center', va='bottom', fontsize=8)",
            "",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md(
            "## 4. Highlight CORDIS rows in the LaTeX output",
            "",
            "For paper figures it's nice to bold-face the proposed algorithms",
            "so the reader's eye lands on them.  This is a post-process on the",
            "LaTeX text from cell 2.",
        ),
        code(
            "tex_with_highlight = tex",
            "for alg in ('CORDIS-Split', 'CORDIS-ADMM'):",
            "    tex_with_highlight = tex_with_highlight.replace(",
            "        f'{alg}', f'\\\\textbf{{{alg}}}'",
            "    )",
            "print(tex_with_highlight)",
        ),
        md("## 5. Figsize variants"),
        GENERIC_FIGSIZE_CELL,
        md("## 6. Save the bar chart with provenance"),
        GENERIC_SAVE_CELL,
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Stage 21 — Array-CDF notebook (sinr_cdf, scnr_cdf from job arrays)
# ─────────────────────────────────────────────────────────────────────

def build_array_cdf_notebook() -> dict:
    cells = [
        md(
            "# Array-CDF Playground",
            "",
            "Interactive exploration of empirical-CDF figures (`sinr_cdf`, `scnr_cdf`)",
            "from **SLURM job-array** runs that have been aggregated by",
            "`scripts/aggregate_array_batch.py`.",
            "",
            "**Why a separate notebook?** Array runs produce a per-experiment tree like:",
            "",
            "```",
            "results/exp_sinr_cdf/",
            "├── array_52671898_task_0/        per-task outputs",
            "├── array_52671898_task_1/",
            "├── ...",
            "├── array_52671898_aggregated/    ← merged result (this is what we load)",
            "└── latest -> array_52671898_task_9/  (after rsync, often points at the wrong dir!)",
            "```",
            "",
            "The `latest` symlink is unreliable after `sync_results_from_hpc3.sh` — sync",
            "order can land it on a per-task dir.  This notebook **never** uses `latest`",
            "for array runs.  It picks the most recent `array_<jobid>_aggregated/`",
            "explicitly (highest job ID), or you can pin a specific `ARRAY_ID`.",
            "",
            "**Compatible experiments:** `sinr_cdf`, `scnr_cdf`.",
        ),
        INTRO_SETUP_ARRAY,
        md(
            "## 1. Load aggregated array result",
            "",
            "Set `exp_name` to the family (`'sinr'` or `'scnr'`) and `ARRAY_ID` if you",
            "want to pin a specific SLURM job ID.  Leave `ARRAY_ID = None` to grab the",
            "most recent array (highest job ID under `results/exp_<name>_cdf/`).",
        ),
        code(
            "# ── The two knobs ──",
            "exp_name  = 'sinr'              # 'sinr' or 'scnr'",
            "ARRAY_ID  = None                # e.g. '52671898'; None = most recent",
            "",
            "# Derived names — change `exp_name` above and these update automatically.",
            "EXPERIMENT   = f'{exp_name}_cdf'",
            "METRIC_MIN   = f'min_{exp_name}_db'",
            "METRIC_MEAN  = f'mean_{exp_name}_db'",
            "METRIC_DISPLAY = 'SINR' if exp_name == 'sinr' else 'SCNR'",
            "",
            "result, array_id = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_ID)",
            "print(f'\\nResolved ARRAY_ID = {array_id}')",
        ),
        md(
            "## 2. Inspect aggregated metadata + per-task breakdown",
            "",
            "`array_summary` prints the total trial count, drops, realizations,",
            "and the per-task table (task_id, seed, trials, drops, realizations).",
            "",
            "Seeds in `_array_common.sh` follow `SEED = BASE_SEED + ARRAY_TASK_ID`,",
            "so they should form a contiguous range — e.g. `42-51` for a 10-task run",
            "with the default `BASE_SEED=42`.  A gap signals a task that failed and",
            "wasn't re-submitted.",
        ),
        code(
            "array_summary(result, EXPERIMENT, array_id)",
        ),
        md(
            "Programmatic access to the same data via `per_task_summary` (returns",
            "a list of dicts):",
        ),
        code(
            "rows = per_task_summary(EXPERIMENT, array_id)",
            "print(f'{len(rows)} task records.')",
            "if rows:",
            "    print(f'First task: {rows[0]}')",
            "# Total-trials cross-check.",
            "total = sum(r['n_trials'] for r in rows)",
            "print(f'Sum of per-task trials: {total}')",
        ),
        md(
            "## 3. Quick CDF — all algorithms",
            "",
            "The aggregated `result.sim_result` has the merged per-trial arrays",
            "(`min_sinr_per_trial`, etc.) — these concatenate cleanly across",
            "tasks, so the CDF spans the full `n_trials_total`.",
        ),
        code(
            "from cordis.plotting import plot_cdf, figsize",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax)",
            "ax.set_title(f'{EXPERIMENT} (array {array_id}): min-{METRIC_DISPLAY} CDF')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        md(
            "## 4. Filter algorithms via `only=`",
            "",
            "Restrict the plot to a hand-picked algorithm subset — same syntax as the",
            "non-array CDF playground.",
        ),
        code(
            "PICK = ['CORDIS-Split', 'CORDIS-ADMM', 'Centralized']",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "ax.set_title(f'{EXPERIMENT} (array {array_id}): CORDIS vs. Centralized')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        md(
            "## 5. SINR floor (γ) + infeasibility annotation",
            "",
            "`plot_cdf` (Stage 20) supports three γ-related kwargs:",
            "",
            "- **`gamma_db=<value>`**: draws a vertical dashed line at γ and, with the",
            "  default `annotate_infeasibility=True`, appends `(inf=X.X%)` to each",
            "  algorithm's legend label showing the fraction of trials with",
            "  `min_sinr_db < γ`.",
            "- **`show_feasible_only=True`**: replaces the full CDF with a",
            "  conditional CDF over only the trials where the algorithm satisfied",
            "  the floor (`min_sinr_db >= γ`).  Requires `gamma_db` to be set;",
            "  warns and falls back to the full CDF if every trial is infeasible.",
            "- **`annotate_infeasibility=False`**: turns off the legend annotation",
            "  if you want clean labels.",
            "",
            "The annotation correctly handles `text.usetex=True` (auto-escapes `%`",
            "so it isn't eaten as a LaTeX comment).",
        ),
        code(
            "# Full CDFs annotated with infeasibility rate at γ = 5 dB.",
            "GAMMA_DB = 5.0",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(",
            "    result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK,",
            "    gamma_db=GAMMA_DB,",
            "    show_feasible_only=False,        # full CDF",
            "    annotate_infeasibility=True,     # show (inf=X.X%) in legend",
            ")",
            "ax.set_title(f'{EXPERIMENT}: full CDF with γ={GAMMA_DB:.0f} dB')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        code(
            "# Feasible-only conditional CDF: only trials where each algorithm",
            "# satisfied the γ floor.  Useful for showing CORDIS-ADMM's behavior",
            "# on the trials where it actually solved the problem, separated from",
            "# its infeasibility tail.",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_cdf(",
            "    result.sim_result, metric=METRIC_MIN, ax=ax, only=PICK,",
            "    gamma_db=GAMMA_DB,",
            "    show_feasible_only=True,         # ← conditional only",
            "    annotate_infeasibility=True,     # legend still shows infeasibility rate",
            ")",
            "ax.set_title(f'{EXPERIMENT}: feasible-only CDF at γ={GAMMA_DB:.0f} dB')",
            "ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plt.show()",
        ),
        md(
            "## 6. Min vs. mean comparison",
            "",
            "Pair the worst-user metric (`min_{family}_db`) with the average-user",
            "metric (`mean_{family}_db`) in a 2-up layout.",
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=figsize(width='double', aspect=3/2))",
            "plot_cdf(result.sim_result, metric=METRIC_MIN, ax=axes[0], only=PICK)",
            "axes[0].set_title(f'Worst-user {METRIC_DISPLAY}')",
            "axes[0].set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "plot_cdf(result.sim_result, metric=METRIC_MEAN, ax=axes[1], only=PICK)",
            "axes[1].set_title(f'Average-user {METRIC_DISPLAY}')",
            "axes[1].set_xlabel(f'mean-{METRIC_DISPLAY} [dB]')",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("## 7. Save with provenance metadata"),
        code(
            "from cordis.plotting import save_figure",
            "",
            "out = save_figure(",
            "    fig,",
            "    base_path=f'../figures/playground/{EXPERIMENT}_array_{array_id}',",
            "    formats=('pdf', 'png'),",
            "    metadata={",
            "        'Experiment': EXPERIMENT,",
            "        'ArrayID':    str(array_id),",
            "        'Notebook':   'playground_array_cdf',",
            "    },",
            ")",
            "for p in out:",
            "    print('wrote', p)",
        ),
        md(
            "## 8. Compare multiple array runs (optional)",
            "",
            "Set `ARRAY_A` / `ARRAY_B` to two array IDs to overlay their curves",
            "(e.g. before vs. after a configuration change).  Leave as `None` to skip.",
        ),
        code(
            "ARRAY_A = None    # e.g. '52671898'",
            "ARRAY_B = None    # e.g. '52680001'",
            "",
            "if ARRAY_A and ARRAY_B:",
            "    res_a, _ = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_A)",
            "    res_b, _ = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_B)",
            "    fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "    n_before = len(ax.lines)",
            "    plot_cdf(res_a.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "    n_after_a = len(ax.lines)",
            "    for ln in ax.lines[n_before:n_after_a]:",
            "        ln.set_label(f'{ln.get_label()} (A={ARRAY_A})')",
            "    plot_cdf(res_b.sim_result, metric=METRIC_MIN, ax=ax, only=PICK)",
            "    for ln in ax.lines[n_after_a:]:",
            "        ln.set_linestyle('--')",
            "        ln.set_label(f'{ln.get_label()} (B={ARRAY_B})')",
            "    ax.legend()",
            "    ax.set_title(f'{EXPERIMENT}: array {ARRAY_A} vs. {ARRAY_B}')",
            "    ax.set_xlabel(f'min-{METRIC_DISPLAY} [dB]')",
            "    plt.show()",
            "else:",
            "    print('Set ARRAY_A and ARRAY_B above to enable multi-array overlay.')",
        ),
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Stage 21 — Array-Sweep notebook (snr_sweep, gamma_sweep, ... arrays)
# ─────────────────────────────────────────────────────────────────────

def build_array_sweep_notebook() -> dict:
    cells = [
        md(
            "# Array-Sweep Playground",
            "",
            "Interactive exploration of sweep figures — single-variable parameter",
            "sweeps — from **SLURM job-array** runs that have been aggregated by",
            "`scripts/aggregate_array_batch.py`.",
            "",
            "**Why a separate notebook?** Array runs produce a per-experiment tree like:",
            "",
            "```",
            "results/exp_snr_sweep/",
            "├── array_52671900_task_0/        per-task outputs (one per sweep slice)",
            "├── array_52671900_task_1/",
            "├── ...",
            "├── array_52671900_aggregated/    ← merged result (this is what we load)",
            "└── latest -> array_52671900_task_9/   (after rsync, often points at the wrong dir!)",
            "```",
            "",
            "The `latest` symlink is unreliable after `sync_results_from_hpc3.sh` — sync",
            "order can land it on a per-task dir.  This notebook **never** uses `latest`",
            "for array runs.  It picks the most recent `array_<jobid>_aggregated/`",
            "explicitly (highest job ID), or you can pin a specific `ARRAY_ID`.",
            "",
            "**Compatible experiments:** `snr_sweep`, `gamma_sweep`, `kappa_sweep`,",
            "`clutter_cnr_sweep`, `n_ue_sweep`, `n_ap_sweep`, `antennas_sweep`.",
        ),
        INTRO_SETUP_ARRAY,
        md(
            "## 1. Load aggregated array result",
            "",
            "Set `exp_name` to the sweep parameter (`'snr'`, `'gamma'`, `'kappa'`,",
            "`'clutter_cnr'`, `'n_ue'`, `'n_ap'`, `'antennas'`) and `ARRAY_ID` if you",
            "want to pin a specific SLURM job ID.  Leave `ARRAY_ID = None` to grab the",
            "most recent array (highest job ID under `results/exp_<name>_sweep/`).",
        ),
        code(
            "# ── The two knobs ──",
            "exp_name  = 'snr'               # snr / gamma / kappa / clutter_cnr",
            "                                # / n_ue / n_ap / antennas",
            "ARRAY_ID  = None                # e.g. '52671900'; None = most recent",
            "",
            "EXPERIMENT = f'{exp_name}_sweep'",
            "",
            "result, array_id = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_ID)",
            "assert result.kind == 'sweep', (",
            "    f'This notebook is for sweep experiments; got kind={result.kind}.'",
            ")",
            "print(f'\\nResolved ARRAY_ID = {array_id}')",
        ),
        md(
            "## 2. Inspect aggregated metadata + per-task breakdown",
            "",
            "`array_summary` prints the headline counts (trials, drops, realizations,",
            "tasks, sweep axis) and the per-task table (task_id, seed, trials,",
            "drops, realizations).",
            "",
            "Seeds in `_array_common.sh` follow `SEED = BASE_SEED + ARRAY_TASK_ID`,",
            "so they should form a contiguous range (e.g. `42-51` for a 10-task run",
            "with the default `BASE_SEED=42`).  A gap signals a task that failed and",
            "wasn't re-submitted.",
        ),
        code(
            "array_summary(result, EXPERIMENT, array_id)",
        ),
        md(
            "Programmatic access to the same data via `per_task_summary` (returns",
            "a list of dicts):",
        ),
        code(
            "rows = per_task_summary(EXPERIMENT, array_id)",
            "print(f'{len(rows)} task records.')",
            "if rows:",
            "    print(f'First task: {rows[0]}')",
            "total = sum(r['n_trials'] for r in rows)",
            "print(f'Sum of per-task trials: {total}')",
        ),
        md(
            "**Sweep-specific sanity check.**  Each axis value should have an entry",
            "in `result.sweep_results` keyed by the value itself.  Confirm the",
            "merged result has the expected number of sweep points:",
        ),
        code(
            "axis_values = list(result.sweep_results.keys())",
            "print(f'Sweep axis:    {result.sweep_axis.name}')",
            "print(f'Display:       {result.sweep_axis.display}')",
            "print(f'Values ({len(axis_values)}):   {axis_values}')",
            "",
            "# Per-axis-value algorithm count (should be identical across the sweep).",
            "for v, sr in result.sweep_results.items():",
            "    print(f'  axis={v}:  {len(sr.algorithm_results)} algorithms')",
        ),
        md(
            "## 3. Quick sweep plot — one metric, all algorithms",
            "",
            "`plot_sweep` takes the keyed-by-x results dict; its x-axis comes",
            "from the dict's keys.  The `sweep_axis.display` metadata supplies",
            "the human-readable axis label.",
        ),
        code(
            "from cordis.plotting import plot_sweep, figsize",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax)",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('min-SINR [dB]')",
            "ax.set_title(f'{EXPERIMENT} (array {array_id}): '",
            "             f'min-SINR vs. {result.sweep_axis.display}')",
            "plt.show()",
        ),
        md(
            "## 4. Side-by-side: SINR + SCNR",
            "",
            "Most paper figures pair a communication metric (min-SINR) with a",
            "sensing metric (mean-SCNR).  Build the two-panel layout inline.",
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=figsize(width='double', aspect=2.5/1.5))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=axes[0])",
            "axes[0].set_xlabel(result.sweep_axis.display)",
            "axes[0].set_ylabel('min-SINR [dB]')",
            "axes[0].set_title('min-SINR [dB]')",
            "plot_sweep(result.sweep_results, metric='mean_scnr_db', ax=axes[1])",
            "axes[1].set_xlabel(result.sweep_axis.display)",
            "axes[1].set_ylabel('mean-SCNR [dB]')",
            "axes[1].set_title('mean-SCNR [dB]')",
            "plt.tight_layout()",
            "plt.show()",
        ),
        md(
            "## 5. Algorithm filter — focus on CORDIS vs. Centralized",
            "",
            "`plot_sweep` honors the same `only=` keyword as `plot_cdf`.",
        ),
        code(
            "PICK = ['CORDIS-Split', 'CORDIS-ADMM', 'Centralized']",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('min-SINR [dB]')",
            "ax.set_title(f'{EXPERIMENT} (array {array_id}): CORDIS vs. Centralized')",
            "plt.show()",
        ),
        md(
            "## 6. Log-y for SCNR sweeps",
            "",
            "Sensing metrics often span orders of magnitude across the sweep range.",
            "Useful for `clutter_cnr_sweep` and `kappa_sweep` especially.",
        ),
        code(
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='mean_scnr_db', ax=ax, only=PICK)",
            "ax.set_yscale('log')",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('mean SCNR (log scale)')",
            "ax.set_title(f'{EXPERIMENT} (array {array_id}): mean-SCNR (log)')",
            "plt.show()",
        ),
        md(
            "## 7. Annotate the operating point",
            "",
            "If your paper highlights a specific axis value (e.g. SNR=10 dB), draw",
            "a vertical line + label at that point.",
        ),
        code(
            "# Set OPERATING_POINT to one of the sweep axis values.  None disables.",
            "OPERATING_POINT = None       # e.g. 10  (for snr_sweep)",
            "",
            "fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "plot_sweep(result.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "if OPERATING_POINT is not None and OPERATING_POINT in result.sweep_results:",
            "    ax.axvline(OPERATING_POINT, color='k', linestyle=':',",
            "               linewidth=0.8, alpha=0.6,",
            "               label=f'{result.sweep_axis.display} = {OPERATING_POINT}')",
            "    ax.legend()",
            "ax.set_xlabel(result.sweep_axis.display)",
            "ax.set_ylabel('min-SINR [dB]')",
            "plt.show()",
        ),
        md("## 8. Save with provenance metadata"),
        code(
            "from cordis.plotting import save_figure",
            "",
            "out = save_figure(",
            "    fig,",
            "    base_path=f'../figures/playground/{EXPERIMENT}_array_{array_id}',",
            "    formats=('pdf', 'png'),",
            "    metadata={",
            "        'Experiment': EXPERIMENT,",
            "        'ArrayID':    str(array_id),",
            "        'SweepAxis':  result.sweep_axis.name,",
            "        'Notebook':   'playground_array_sweep',",
            "    },",
            ")",
            "for p in out:",
            "    print('wrote', p)",
        ),
        md(
            "## 9. Compare multiple array runs (optional)",
            "",
            "Set `ARRAY_A` / `ARRAY_B` to two array IDs to overlay their curves",
            "(e.g. before vs. after a configuration change).  Leave as `None` to skip.",
        ),
        code(
            "ARRAY_A = None    # e.g. '52671900'",
            "ARRAY_B = None    # e.g. '52680005'",
            "",
            "if ARRAY_A and ARRAY_B:",
            "    res_a, _ = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_A)",
            "    res_b, _ = load_aggregated_array_result(EXPERIMENT, array_id=ARRAY_B)",
            "    fig, ax = plt.subplots(figsize=figsize(width='single', aspect=3/2))",
            "    n_before = len(ax.lines)",
            "    plot_sweep(res_a.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "    n_after_a = len(ax.lines)",
            "    for ln in ax.lines[n_before:n_after_a]:",
            "        ln.set_label(f'{ln.get_label()} (A={ARRAY_A})')",
            "    plot_sweep(res_b.sweep_results, metric='min_sinr_db', ax=ax, only=PICK)",
            "    for ln in ax.lines[n_after_a:]:",
            "        ln.set_linestyle('--')",
            "        ln.set_label(f'{ln.get_label()} (B={ARRAY_B})')",
            "    ax.legend()",
            "    ax.set_xlabel(res_a.sweep_axis.display)",
            "    ax.set_ylabel('min-SINR [dB]')",
            "    ax.set_title(f'{EXPERIMENT}: array {ARRAY_A} vs. {ARRAY_B}')",
            "    plt.show()",
            "else:",
            "    print('Set ARRAY_A and ARRAY_B above to enable multi-array overlay.')",
        ),
    ]
    return notebook(cells)


# ─────────────────────────────────────────────────────────────────────
#  Build all six
# ─────────────────────────────────────────────────────────────────────

NOTEBOOKS = {
    "playground_cdf.ipynb":          build_cdf_notebook,
    "playground_sweep.ipynb":        build_sweep_notebook,
    "playground_trace.ipynb":        build_trace_notebook,
    "playground_table.ipynb":        build_table_notebook,
    "playground_array_cdf.ipynb":    build_array_cdf_notebook,
    "playground_array_sweep.ipynb":  build_array_sweep_notebook,
}


def main() -> None:
    for filename, builder in NOTEBOOKS.items():
        nb = builder()
        path = HERE / filename
        with open(path, "w") as f:
            json.dump(nb, f, indent=1)
            f.write("\n")
        n_cells = len(nb["cells"])
        print(f"  wrote {path.name}  ({n_cells} cells)")
    print(f"\nTotal: {len(NOTEBOOKS)} notebooks regenerated.")


if __name__ == "__main__":
    main()

