#!/usr/bin/env python3
"""
scripts/exp_convergence_trace.py
================================

ADMM primal/dual residual + objective trajectory on one trial.

Run via the matching shell wrapper::

    bash scripts/exp_convergence_trace.sh

…or directly::

    python3 scripts/exp_convergence_trace.py --help

Generated by scripts/regenerate_experiment_scripts.py — edit the metadata
table in that file (not this one) if behaviour needs to change.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _exp_common import (    # noqa: E402
    build_base_parser,
    add_drops_args,
    parse_value_list,
    run_experiment,
)


def main() -> None:
    parser = build_base_parser("convergence_trace")
    add_drops_args(parser)
    parser.add_argument("--drop-seed", type=int, default=None,
                        help='Topology drop seed for the single trial. Empty → use registry default.')
    parser.add_argument("--realization-seed", type=int, default=None,
                        help='Channel realisation seed for the single trial. Empty → use registry default.')
    parser.add_argument("--n-admm-max", type=int, default=None,
                        help='Cap on ADMM iterations. Empty → use registry default (set in cordis/experiments/registry.py).')
    args = parser.parse_args()

    extra_kwargs = {
        "drop_seed": args.drop_seed,
        "realization_seed": args.realization_seed,
        "n_admm_max": args.n_admm_max,
    }
    # Drop any None-valued sweep ranges so the registry uses its defaults.
    extra_kwargs = {k: v for k, v in extra_kwargs.items() if v is not None}

    # Per-experiment fallback drops × real (used only if CLI args don't
    # specify trial counts and config has no simulation.n_trials).
    run_experiment("convergence_trace", args, extra_kwargs,
                   fallback_n_drops=1,
                   fallback_n_real=1)


if __name__ == "__main__":
    main()
