#!/usr/bin/env python3
"""
scripts/exp_sinr_cdf.py
=======================

Empirical CDF of per-user min-SINR across many trials.

Run via the matching shell wrapper::

    bash scripts/exp_sinr_cdf.sh

…or directly::

    python3 scripts/exp_sinr_cdf.py --help

Generated by scripts/regenerate_experiment_scripts.py — edit the metadata
table in that file (not this one) if behaviour needs to change.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _exp_common import (    # noqa: E402
    build_base_parser,
    add_cdf_args,
    parse_value_list,
    run_experiment,
)


def main() -> None:
    parser = build_base_parser("sinr_cdf")
    add_cdf_args(parser,
                          default_n_drops=50,
                          default_n_real=4)

    args = parser.parse_args()

    extra_kwargs = {
        "n_drops":        args.n_drops,
        "n_realizations": args.n_realizations,

    }
    # Drop any None-valued sweep ranges so the registry uses its defaults.
    extra_kwargs = {k: v for k, v in extra_kwargs.items() if v is not None}

    run_experiment("sinr_cdf", args, extra_kwargs)


if __name__ == "__main__":
    main()
