#!/usr/bin/env bash
# =============================================================================
# scripts/exp_clutter_cnr_sweep.sh
# =============================================================================
#
# min-SINR & sum-SCNR vs clutter-to-noise ratio (CNR) [dB].
#
# Wrapper around scripts/exp_clutter_cnr_sweep.py that sets defaults appropriate
# for the journal paper.  Edit the OPTIONS block to customise.
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.." || { echo "ERROR: could not find repo root"; exit 1; }

if [ -f ".venv/bin/activate" ]; then source .venv/bin/activate
elif [ -f "venv/bin/activate" ]; then source venv/bin/activate
fi

# Ensure cordis is importable without requiring `pip install -e .`
export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

# ─── OPTIONS — edit these ────────────────────────────────────────────
BASE_CONFIG="${BASE_CONFIG:-configs/default.json}"
EXP_CONFIG="${EXP_CONFIG:-configs/exp_clutter_cnr_sweep.json}"   # generated by configs/recipes/exp_clutter_cnr_sweep.sh
N_DROPS="${N_DROPS:-20}"
N_REAL="${N_REAL:-2}"
N_WORKERS="${N_WORKERS:--1}"          # -1 = all cores; 1 = sequential
SEED="${SEED:-42}"
OUTPUT_ROOT="${OUTPUT_ROOT:-results}"
CNR_VALUES_DB="${CNR_VALUES_DB:-}"

# ─── Run ─────────────────────────────────────────────────────────────
EXP_CONFIG_FLAG=""
if [ -f "$EXP_CONFIG" ]; then EXP_CONFIG_FLAG="--exp-config $EXP_CONFIG"; fi

python3 scripts/exp_clutter_cnr_sweep.py \
    --base-config   "$BASE_CONFIG"   \
    $EXP_CONFIG_FLAG                 \
    --n-drops       "$N_DROPS"       \
    --n-realizations "$N_REAL"       \
    --n-workers     "$N_WORKERS"     \
    --seed          "$SEED"          \
    --output-root   "$OUTPUT_ROOT"   \
    --cnr-values-db    "$CNR_VALUES_DB"   \
    "$@"
