#!/usr/bin/env python3
"""
scripts/exp_clutter_cnr_sweep.py
================================

min-SINR & sum-SCNR vs clutter-to-noise ratio (CNR) [dB].

Run via the matching shell wrapper::

    bash scripts/exp_clutter_cnr_sweep.sh

…or directly::

    python3 scripts/exp_clutter_cnr_sweep.py --help

Generated by scripts/regenerate_experiment_scripts.py — edit the metadata
table in that file (not this one) if behaviour needs to change.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _exp_common import (    # noqa: E402
    build_base_parser,
    add_sweep_args,
    parse_value_list,
    run_experiment,
)


def main() -> None:
    parser = build_base_parser("clutter_cnr_sweep")
    add_sweep_args(parser,
                          default_n_drops=20,
                          default_n_real=2)
    parser.add_argument("--cnr-values-db", default='',
                        help='Comma- or space-separated CNR values in dB. Empty → use registry default.')
    args = parser.parse_args()

    extra_kwargs = {
        "n_drops":        args.n_drops,
        "n_realizations": args.n_realizations,
        "cnr_values_db": parse_value_list(args.cnr_values_db, float) or None,
    }
    # Drop any None-valued sweep ranges so the registry uses its defaults.
    extra_kwargs = {k: v for k, v in extra_kwargs.items() if v is not None}

    run_experiment("clutter_cnr_sweep", args, extra_kwargs)


if __name__ == "__main__":
    main()
