#!/usr/bin/env bash
# =============================================================================
# scripts/exp_n_ap_sweep.sh
# =============================================================================
#
# min-SINR & sum-SCNR vs number of APs.
#
# Wrapper around scripts/exp_n_ap_sweep.py.  Every knob below is listed for
# discoverability — most of them have NO default in this file so the
# values come from the JSON config (the single source of truth).
# Override any of them at the command line, e.g.:
#
#     N_TRIALS=500 bash scripts/exp_n_ap_sweep.sh
#     SEED=123 OUTPUT_ROOT=/scratch/results bash scripts/exp_n_ap_sweep.sh
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.." || { echo "ERROR: could not find repo root"; exit 1; }

if [ -f ".venv/bin/activate" ]; then source .venv/bin/activate
elif [ -f "venv/bin/activate" ]; then source venv/bin/activate
fi

# Ensure cordis is importable without requiring `pip install -e .`
export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

# ─── OPTIONS — empty values fall through to the JSON config ──────────
# Config-file pointers (paths, NOT config parameters):
BASE_CONFIG="${BASE_CONFIG:-configs/default.json}"
EXP_CONFIG="${EXP_CONFIG:-configs/exp_n_ap_sweep.json}"   # generated by configs/recipes/exp_n_ap_sweep.sh
# Trial-count knobs — set EITHER N_TRIALS (auto-decompose into drops×real)
# OR N_DROPS and N_REAL explicitly.  Empty → use config simulation.n_trials.
N_DROPS="${N_DROPS:-}"
N_REAL="${N_REAL:-}"
N_TRIALS="${N_TRIALS:-}"
# Non-config knob (no entry in the JSON config):
N_WORKERS="${N_WORKERS:--1}"          # -1 = all cores; 1 = sequential
# Config-backed knobs — empty → use the JSON config value:
SEED="${SEED:-}"                      # default: config simulation.seed
OUTPUT_ROOT="${OUTPUT_ROOT:-}"        # default: config simulation.output_root
RUN_ID="${RUN_ID:-}"                  # empty → runner auto-timestamps the leaf dir
# Algorithm selection — empty → 'all_algorithms' (the default for
# every CDF and sweep experiment since Stage 17; silently ignored by
# convergence_trace and fronthaul_table).  Override with one of:
# cordis_only, cordis_vs_centralized, cordis_vs_benchmarks,
# all_algorithms.
SPECS="${SPECS:-}"
N_AP_VALUES="${N_AP_VALUES:-}"

# ─── Run ─────────────────────────────────────────────────────────────
EXP_CONFIG_FLAG=""
if [ -f "$EXP_CONFIG" ]; then EXP_CONFIG_FLAG="--exp-config $EXP_CONFIG"; fi

# Conditionally include flags so empty env vars don't override the
# config.  Pattern: only add the flag if the user explicitly set it.
TRIAL_ARGS=()
[ -n "$N_DROPS"  ] && TRIAL_ARGS+=(--n-drops       "$N_DROPS")
[ -n "$N_REAL"   ] && TRIAL_ARGS+=(--n-realizations "$N_REAL")
[ -n "$N_TRIALS" ] && TRIAL_ARGS+=(--n-trials      "$N_TRIALS")

# Conditionally include --specs.  Empty means "use per-experiment default".
SPEC_ARGS=()
[ -n "$SPECS" ] && SPEC_ARGS+=(--specs "$SPECS")

# Conditionally include --run-id.  Empty means "use auto-timestamp".
# SLURM array jobs set this so each task gets a unique, predictable
# leaf dir (e.g. array_12345_task_0) instead of racing timestamps.
RUN_ID_ARGS=()
[ -n "$RUN_ID" ] && RUN_ID_ARGS+=(--run-id "$RUN_ID")

# Conditionally include --seed / --output-root.  Empty means
# "let the runner read the value from the config file".
SEED_ARGS=()
[ -n "$SEED" ] && SEED_ARGS+=(--seed "$SEED")
OUTPUT_ROOT_ARGS=()
[ -n "$OUTPUT_ROOT" ] && OUTPUT_ROOT_ARGS+=(--output-root "$OUTPUT_ROOT")

# Conditionally include sweep / experiment-specific flags.
# Empty env var → no --flag passed → registry default applies.
SWEEP_ARGS=()
[ -n "$N_AP_VALUES" ] && SWEEP_ARGS+=(--n-ap-values "$N_AP_VALUES")
python3 scripts/exp_n_ap_sweep.py \
    --base-config   "$BASE_CONFIG"   \
    $EXP_CONFIG_FLAG                 \
    "${TRIAL_ARGS[@]}"             \
    "${SPEC_ARGS[@]}"              \
    "${RUN_ID_ARGS[@]}"            \
    "${SEED_ARGS[@]}"              \
    "${OUTPUT_ROOT_ARGS[@]}"       \
    --n-workers     "$N_WORKERS"     \
    "${SWEEP_ARGS[@]}"             \
    "$@"
