#!/usr/bin/env bash
# =============================================================================
# scripts/exp_convergence_trace.sh
# =============================================================================
#
# ADMM primal/dual residual + objective trajectory on one trial.
#
# Wrapper around scripts/exp_convergence_trace.py that sets defaults appropriate
# for the journal paper.  Edit the OPTIONS block to customise.
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.." || { echo "ERROR: could not find repo root"; exit 1; }

if [ -f ".venv/bin/activate" ]; then source .venv/bin/activate
elif [ -f "venv/bin/activate" ]; then source venv/bin/activate
fi

# ─── OPTIONS — edit these ────────────────────────────────────────────
BASE_CONFIG="${BASE_CONFIG:-configs/default.json}"
EXP_CONFIG="${EXP_CONFIG:-configs/exp_convergence_trace.json}"   # generated by configs/recipes/exp_convergence_trace.sh
N_DROPS="${N_DROPS:-1}"
N_REAL="${N_REAL:-1}"
N_WORKERS="${N_WORKERS:--1}"          # -1 = all cores; 1 = sequential
SEED="${SEED:-42}"
OUTPUT_ROOT="${OUTPUT_ROOT:-results}"
DROP_SEED="${DROP_SEED:-42}"
REALIZATION_SEED="${REALIZATION_SEED:-43}"
N_ADMM_MAX="${N_ADMM_MAX:-80}"

# ─── Run ─────────────────────────────────────────────────────────────
EXP_CONFIG_FLAG=""
if [ -f "$EXP_CONFIG" ]; then EXP_CONFIG_FLAG="--exp-config $EXP_CONFIG"; fi

python3 scripts/exp_convergence_trace.py \
    --base-config   "$BASE_CONFIG"   \
    $EXP_CONFIG_FLAG                 \
    --n-drops       "$N_DROPS"       \
    --n-realizations "$N_REAL"       \
    --n-workers     "$N_WORKERS"     \
    --seed          "$SEED"          \
    --output-root   "$OUTPUT_ROOT"   \
    --drop-seed    "$DROP_SEED"   \
    --realization-seed    "$REALIZATION_SEED"   \
    --n-admm-max    "$N_ADMM_MAX"   \
    "$@"
