#!/usr/bin/env bash
# =============================================================================
# scripts/exp_clutter_cnr_sweep.sh
# =============================================================================
#
# min-SINR & sum-SCNR vs clutter-to-noise ratio (CNR) [dB].
#
# Wrapper around scripts/exp_clutter_cnr_sweep.py that sets defaults appropriate
# for the journal paper.  Edit the OPTIONS block to customise.
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.." || { echo "ERROR: could not find repo root"; exit 1; }

if [ -f ".venv/bin/activate" ]; then source .venv/bin/activate
elif [ -f "venv/bin/activate" ]; then source venv/bin/activate
fi

# Ensure cordis is importable without requiring `pip install -e .`
export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

# ─── OPTIONS — edit these ────────────────────────────────────────────
BASE_CONFIG="${BASE_CONFIG:-configs/default.json}"
EXP_CONFIG="${EXP_CONFIG:-configs/exp_clutter_cnr_sweep.json}"   # generated by configs/recipes/exp_clutter_cnr_sweep.sh
# Trial-count knobs — set EITHER N_TRIALS (auto-decompose into drops×real)
# OR N_DROPS and N_REAL explicitly.  See `python3 scripts/exp_clutter_cnr_sweep.py --help`.
# Per-experiment fallback when nothing else is set: 20 drops × 2 real.
N_DROPS="${N_DROPS:-}"
N_REAL="${N_REAL:-}"
N_TRIALS="${N_TRIALS:-}"
N_WORKERS="${N_WORKERS:--1}"          # -1 = all cores; 1 = sequential
SEED="${SEED:-42}"
OUTPUT_ROOT="${OUTPUT_ROOT:-results}"
RUN_ID="${RUN_ID:-}"                  # custom run-id; empty → auto-timestamp
# Algorithm selection — leave empty to use the per-experiment default
# (sinr_cdf/scnr_cdf → all_algorithms; gamma/kappa/clutter sweeps →
# cordis_vs_centralized; antennas_sweep → cordis_vs_benchmarks).  Set
# to one of: cordis_only, cordis_vs_centralized, cordis_vs_benchmarks,
# all_algorithms — to override.
SPECS="${SPECS:-}"
CNR_VALUES_DB="${CNR_VALUES_DB:-}"

# ─── Run ─────────────────────────────────────────────────────────────
EXP_CONFIG_FLAG=""
if [ -f "$EXP_CONFIG" ]; then EXP_CONFIG_FLAG="--exp-config $EXP_CONFIG"; fi

# Conditionally include trial-count flags so the resolver can pick the
# right precedence path (explicit → n_trials → config → defaults).
TRIAL_ARGS=()
[ -n "$N_DROPS"  ] && TRIAL_ARGS+=(--n-drops       "$N_DROPS")
[ -n "$N_REAL"   ] && TRIAL_ARGS+=(--n-realizations "$N_REAL")
[ -n "$N_TRIALS" ] && TRIAL_ARGS+=(--n-trials      "$N_TRIALS")

# Conditionally include --specs.  Empty means "use per-experiment default".
SPEC_ARGS=()
[ -n "$SPECS" ] && SPEC_ARGS+=(--specs "$SPECS")

# Conditionally include --run-id.  Empty means "use auto-timestamp".
# SLURM array jobs set this so each task gets a unique, predictable
# leaf dir (e.g. array_12345_task_0) instead of racing timestamps.
RUN_ID_ARGS=()
[ -n "$RUN_ID" ] && RUN_ID_ARGS+=(--run-id "$RUN_ID")

python3 scripts/exp_clutter_cnr_sweep.py \
    --base-config   "$BASE_CONFIG"   \
    $EXP_CONFIG_FLAG                 \
    "${TRIAL_ARGS[@]}"             \
    "${SPEC_ARGS[@]}"              \
    "${RUN_ID_ARGS[@]}"            \
    --n-workers     "$N_WORKERS"     \
    --seed          "$SEED"          \
    --output-root   "$OUTPUT_ROOT"   \
    --cnr-values-db    "$CNR_VALUES_DB"   \
    "$@"
