#!/usr/bin/env python3
"""
scripts/exp_fronthaul_table.py
==============================

Per-AP fronthaul coordination overhead for each algorithm.

Run via the matching shell wrapper::

    bash scripts/exp_fronthaul_table.sh

…or directly::

    python3 scripts/exp_fronthaul_table.py --help

Generated by scripts/regenerate_experiment_scripts.py — edit the metadata
table in that file (not this one) if behaviour needs to change.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _exp_common import (    # noqa: E402
    build_base_parser,
    add_sweep_args,
    parse_value_list,
    run_experiment,
)


def main() -> None:
    parser = build_base_parser("fronthaul_table")
    add_sweep_args(parser)
    parser.add_argument("--n-admm-drops", type=int, default=20,
                        help='Drops used to estimate average ADMM iteration count.')
    args = parser.parse_args()

    extra_kwargs = {
        "n_admm_drops": args.n_admm_drops,
    }
    # Drop any None-valued sweep ranges so the registry uses its defaults.
    extra_kwargs = {k: v for k, v in extra_kwargs.items() if v is not None}

    # Per-experiment fallback drops × real (used only if CLI args don't
    # specify trial counts and config has no simulation.n_trials).
    run_experiment("fronthaul_table", args, extra_kwargs,
                   fallback_n_drops=20,
                   fallback_n_real=2)


if __name__ == "__main__":
    main()
