#!/usr/bin/env python3
"""
scripts/exp_convergence_trace.py
================================

ADMM primal/dual residual + objective trajectory on one trial.

Run via the matching shell wrapper::

    bash scripts/exp_convergence_trace.sh

…or directly::

    python3 scripts/exp_convergence_trace.py --help

Generated by scripts/regenerate_experiment_scripts.py — edit the metadata
table in that file (not this one) if behaviour needs to change.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _exp_common import (    # noqa: E402
    build_base_parser,
    add_drops_args,
    parse_value_list,
    run_experiment,
)


def main() -> None:
    parser = build_base_parser("convergence_trace")
    add_drops_args(parser,
                          default_n_drops=1,
                          default_n_real=1)
    parser.add_argument("--drop-seed", type=int, default=42,
                        help='Topology drop seed for the single trial.')
    parser.add_argument("--realization-seed", type=int, default=43,
                        help='Channel realisation seed for the single trial.')
    parser.add_argument("--n-admm-max", type=int, default=80,
                        help='Cap on ADMM iterations.')
    args = parser.parse_args()

    extra_kwargs = {
        "n_drops":        args.n_drops,
        "n_realizations": args.n_realizations,
        "drop_seed": args.drop_seed,
        "realization_seed": args.realization_seed,
        "n_admm_max": args.n_admm_max,
    }
    # Drop any None-valued sweep ranges so the registry uses its defaults.
    extra_kwargs = {k: v for k, v in extra_kwargs.items() if v is not None}

    run_experiment("convergence_trace", args, extra_kwargs)


if __name__ == "__main__":
    main()
