#!/usr/bin/env python3
"""
scripts/plot_convergence_trace.py
=================================

Render the paper figure for the 'convergence_trace' experiment.

Loads the most recent results/exp_convergence_trace/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_convergence_trace/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("convergence_trace").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("convergence_trace", args)

    apply_paper_style()
    ax_top, ax_bot = plot_admm_convergence(result.admm_result, log_y=True)
    fig = ax_top.figure
    save_paper_figure(fig, "convergence_trace", args,
                      experiment_name="convergence_trace")
    plt.close(fig)

if __name__ == "__main__":
    main()
