#!/usr/bin/env python3
"""
scripts/plot_gamma_sweep.py
===========================

Render the paper figure for the 'gamma_sweep' experiment.

Loads the most recent results/exp_gamma_sweep/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_gamma_sweep/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make `cordis` and the sibling `_plot_common` helpers importable when
# this script is run directly (e.g. `python3 scripts/plot_gamma_sweep.py`).
# The runner picks up this script's directory (scripts/) for siblings
# AND its parent (the repo root) for the in-tree cordis package.
_HERE      = Path(__file__).resolve().parent          # scripts/
_REPO_ROOT = _HERE.parent                              # repo root
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_REPO_ROOT))

from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("gamma_sweep").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("gamma_sweep", args)

    fig, _ = sweep_plot_pair(
        result,
        metric_top="min_sinr_db",  ylabel_top=r"min-SINR [dB]",
        metric_bot="sum_scnr_db",  ylabel_bot=r"sum-SCNR [dB]",
        xlabel=r"$\gamma$ [dB]",
    )
    save_paper_figure(fig, "gamma_sweep", args, experiment_name="gamma_sweep")
    plt.close(fig)

if __name__ == "__main__":
    main()
