#!/usr/bin/env python3
"""
scripts/plot_fronthaul_table.py
===============================

Render the paper figure for the 'fronthaul_table' experiment.

Loads the most recent results/exp_fronthaul_table/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_fronthaul_table/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make `cordis` and the sibling `_plot_common` helpers importable when
# this script is run directly (e.g. `python3 scripts/plot_fronthaul_table.py`).
# The runner picks up this script's directory (scripts/) for siblings
# AND its parent (the repo root) for the in-tree cordis package.
_HERE      = Path(__file__).resolve().parent          # scripts/
_REPO_ROOT = _HERE.parent                              # repo root
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_REPO_ROOT))

from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("fronthaul_table").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("fronthaul_table", args)

    # fronthaul_table emits a Markdown + LaTeX table rather than a figure.
    import json

    out_dir = resolve_output_dir("fronthaul_table", args)
    table   = result.table_data
    md      = result.metadata

    # ── Markdown ─────────────────────────────────────────────────────────
    md_lines = ["# Fronthaul Coordination Overhead per AP",
                "",
                f"_Scenario: M={md.get('M')}, "
                f"N_UE={md.get('n_ue')}, "
                f"N_targets={md.get('n_targets')}, "
                f"|D|={md.get('n_streams')}_",
                "",
                f"_Average ADMM iterations: T_ADMM = "
                f"{md.get('admm_avg_iters', float('nan')):.2f}_",
                "",
                "| Algorithm | Data shared | Size | Real scalars / round | Scales with | Scalable |",
                "|---|---|---|---|---|---|"]
    for algo, row in table.items():
        rs = row.get("real_scalars")
        rs_str = "—" if rs is None else (
            f"{rs:.1f}" if isinstance(rs, float) else f"{rs:d}"
        )
        md_lines.append(
            f"| {algo} | {row['data_to_share']} | {row['size']} | "
            f"{rs_str} | {row['scales_with']} | "
            f"{'✓' if row['scalable'] else '✗'} |"
        )
    md_path = out_dir / "fronthaul_table.md"
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    log.info("Wrote %s", md_path)

    # ── LaTeX ────────────────────────────────────────────────────────────
    tex = ["\\begin{table}[t]",
           "\\centering",
           "\\caption{Per-AP fronthaul coordination overhead.}",
           "\\label{tab:fronthaul}",
           "\\begin{tabular}{lcccc}",
           "\\toprule",
           "Algorithm & Data shared & Size & Real / iter & Scalable \\\\",
           "\\midrule"]
    for algo, row in table.items():
        rs = row.get("real_scalars")
        rs_str = "--" if rs is None else (
            f"{rs:.1f}" if isinstance(rs, float) else f"{rs:d}"
        )
        tex.append(
            f"{algo} & {row['data_to_share']} & {row['size']} & "
            f"{rs_str} & {'$\\checkmark$' if row['scalable'] else '$\\times$'} \\\\"
        )
    tex += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    tex_path = out_dir / "fronthaul_table.tex"
    tex_path.write_text("\n".join(tex) + "\n", encoding="utf-8")
    log.info("Wrote %s", tex_path)

    # ── JSON dump for downstream tooling ─────────────────────────────────
    json_path = out_dir / "fronthaul_table.json"
    json_path.write_text(json.dumps({"table": table, "metadata": md},
                                     indent=2, default=str),
                         encoding="utf-8")
    log.info("Wrote %s", json_path)

if __name__ == "__main__":
    main()
