#!/usr/bin/env python3
"""
scripts/plot_sinr_cdf.py
========================

Render the paper figure for the 'sinr_cdf' experiment.

Loads the most recent results/exp_sinr_cdf/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_sinr_cdf/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("sinr_cdf").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("sinr_cdf", args)

    apply_paper_style()
    fig, ax = plt.subplots(figsize=figsize(width="single", aspect=3.5/2.4))
    plot_cdf(result.sim_result, metric="min_sinr_db",
             xlabel=r"min-SINR [dB]", ax=ax)
    save_paper_figure(fig, "sinr_cdf", args, experiment_name="sinr_cdf")
    plt.close(fig)

if __name__ == "__main__":
    main()
