#!/usr/bin/env python3
"""
scripts/plot_scnr_cdf.py
========================

Render the paper figure for the 'scnr_cdf' experiment.

Loads the most recent results/exp_scnr_cdf/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_scnr_cdf/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make `cordis` and the sibling `_plot_common` helpers importable when
# this script is run directly (e.g. `python3 scripts/plot_scnr_cdf.py`).
# The runner picks up this script's directory (scripts/) for siblings
# AND its parent (the repo root) for the in-tree cordis package.
_HERE      = Path(__file__).resolve().parent          # scripts/
_REPO_ROOT = _HERE.parent                              # repo root
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_REPO_ROOT))

from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("scnr_cdf").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("scnr_cdf", args)

    apply_paper_style()
    fig, ax = plt.subplots(figsize=figsize(width="single", aspect=3.5/2.4))
    plot_cdf(result.sim_result, metric="sum_scnr_db",
             xlabel=r"sum-SCNR [dB]", ax=ax)
    save_paper_figure(fig, "scnr_cdf", args, experiment_name="scnr_cdf")
    plt.close(fig)

if __name__ == "__main__":
    main()
