#!/usr/bin/env python3
"""
scripts/plot_n_ap_sweep.py
==========================

Render the paper figure for the 'n_ap_sweep' experiment.

Loads the most recent results/exp_n_ap_sweep/<ts>/ run (override with
``--exp-dir``) and writes figures into figures/exp_n_ap_sweep/.

Generated by scripts/regenerate_experiment_scripts.py.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Make sibling helpers importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _plot_common import (   # noqa: E402
    build_plot_parser, load_result, save_paper_figure,
    resolve_output_dir, sweep_plot_pair,
)

# Common matplotlib + cordis.plotting bits.
import matplotlib.pyplot as plt    # noqa: E402
from cordis.plotting import (      # noqa: E402
    apply_paper_style, figsize,
    plot_cdf, plot_sweep, plot_admm_convergence,
)

log = logging.getLogger(__name__)


def main() -> None:
    args   = build_plot_parser("n_ap_sweep").parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    result = load_result("n_ap_sweep", args)

    fig, _ = sweep_plot_pair(
        result,
        metric_top="min_sinr_db",  ylabel_top=r"min-SINR [dB]",
        metric_bot="sum_scnr_db",  ylabel_bot=r"sum-SCNR [dB]",
        xlabel=r"$N_{\rm AP}$",
    )
    save_paper_figure(fig, "n_ap_sweep", args, experiment_name="n_ap_sweep")
    plt.close(fig)

if __name__ == "__main__":
    main()
