#!/usr/bin/env bash
# =============================================================================
# scripts/slurm/uci-hpc3/array/_array_common.sh
# =============================================================================
# Shared per-task setup sourced by every UCI HPC3 exp_*.array.sub script.
#
# Each array task gets a unique SEED so numpy SeedSequence yields a
# disjoint trial stream, and writes to its own subdirectory under
# results/array_<jobid>/task_<task_id>/ so concurrent tasks don't
# collide on output filenames.  After the array completes, the
# per-task pickles are merged via scripts/aggregate_array_batch.py.
#
# Knobs (set in the calling .array.sub via env, or override at submit
# time with VAR=value sbatch ...):
#
#   EXP_NAME           experiment name (set by caller, required)
#   N_TRIALS_TOTAL     total trials across the whole array (default 500)
#   N_ARRAY_TASKS      total task count (must match --array=0-(N-1))
#                      (default $SLURM_ARRAY_TASK_COUNT)
#   BASE_SEED          base seed; per-task SEED = BASE_SEED + task_id
#                      (default 42)
#   OUTPUT_ROOT        per-task output root.  Default places all tasks
#                      under results/array_<arrayjobid>/task_<id>/
#
# Generated by scripts/regenerate_experiment_scripts.py.
# =============================================================================

set -euo pipefail

# ── Locate repo + source _config.sh (cluster+personal settings) ─────
if [ -n "${SLURM_SUBMIT_DIR:-}" ]; then
    UCI_DIR="$SLURM_SUBMIT_DIR/scripts/slurm/uci-hpc3"
else
    # _array_common.sh is at .../uci-hpc3/array/, _config.sh at .../uci-hpc3/
    UCI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
fi
# shellcheck source=../_config.sh
source "$UCI_DIR/_config.sh"

# ── Repo + venv + modules ───────────────────────────────────────────
cd "$CORDIS_REPO_DIR"
mkdir -p logs/slurm

module purge
module load "$CORDIS_PYTHON_MODULE"
# shellcheck source=/dev/null
source "$CORDIS_VENV/bin/activate"

# ── Compute per-task trial count + seed ─────────────────────────────
# N_ARRAY_TASKS defaults to whatever SLURM allocated (always available
# inside an array job; falls back to 1 if user invoked the script
# outside SLURM for local debugging).
: "${N_ARRAY_TASKS:=${SLURM_ARRAY_TASK_COUNT:-1}}"
: "${N_TRIALS_TOTAL:=500}"
: "${BASE_SEED:=42}"
: "${ARRAY_TASK_ID:=${SLURM_ARRAY_TASK_ID:-0}}"
: "${ARRAY_JOB_ID:=${SLURM_ARRAY_JOB_ID:-local}}"

# Ceiling division so the final task picks up the remainder when
# N_TRIALS_TOTAL is not divisible by N_ARRAY_TASKS.  Last task may
# do slightly fewer trials than its share; that's fine.
export N_TRIALS=$(( (N_TRIALS_TOTAL + N_ARRAY_TASKS - 1) / N_ARRAY_TASKS ))
# Each task uses a unique base seed; SeedSequence(SEED).spawn(...) is
# prefix-stable so different SEED values yield disjoint streams.
export SEED=$(( BASE_SEED + ARRAY_TASK_ID ))
# Each task writes to its own subdirectory so concurrent writers don't
# collide on auto-generated timestamps.  The aggregator globs the
# array_<jobid>/ parent dir to find them.
export OUTPUT_ROOT="results/array_${ARRAY_JOB_ID}/task_${ARRAY_TASK_ID}"
mkdir -p "$OUTPUT_ROOT"

# Worker count tracks the SLURM allocation (40 by default on HPC3).
export N_WORKERS="${SLURM_CPUS_PER_TASK:-1}"

# Ensure cordis is importable without `pip install -e .`.
export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

# Tag the run so it's identifiable in the per-task output.
export TAG="array_${ARRAY_JOB_ID}_t${ARRAY_TASK_ID}"
