#!/usr/bin/env bash
# =============================================================================
# scripts/slurm/uci-hpc3/array/_array_common.sh
# =============================================================================
# Shared per-task setup sourced by every UCI HPC3 exp_*.array.sub script.
#
# Each array task gets a unique SEED so numpy SeedSequence yields a
# disjoint trial stream, and a unique RUN_ID so the runner places its
# output under a predictable leaf dir.  After all tasks complete, the
# per-task results are merged via scripts/aggregate_array_batch.py.
#
# Directory layout (experiment-first — Stage 21 revision):
#
#   results/exp_<name>/array_<jobid>_task_<id>/         (per-task output)
#       result.npz | result_<axis>_<v>.npz             (single | sweep)
#       result.json (sidecar)
#       manifest.json
#       logs/run.log
#
#   results/exp_<name>/array_<jobid>_aggregated/        (after aggregator)
#       result.npz | result_<axis>_<v>.npz (merged)
#       result.json (merged sidecar)
#       manifest.json
#
# This layout means `bash scripts/sync_results_from_hpc3.sh exp_sinr_cdf`
# brings down every array run + the aggregated result in one go; no
# special-casing needed in the sync script.
#
# Knobs (set in the calling .array.sub via env, or override at submit
# time with VAR=value sbatch ...):
#
#   EXP_NAME           experiment name (set by caller, required)
#   N_TRIALS_TOTAL     total trials across the whole array.
#                      Default: read from cfg.simulation.n_trials of
#                      the experiment config (configs/exp_<name>.json),
#                      falling back to configs/default.json, then to
#                      500 only if neither file exists.
#   N_ARRAY_TASKS      total task count (must match --array=0-(N-1))
#                      (default $SLURM_ARRAY_TASK_COUNT)
#   BASE_SEED          base seed; per-task SEED = BASE_SEED + task_id.
#                      Default: read from cfg.simulation.seed of the
#                      experiment config (configs/exp_<name>.json),
#                      falling back to configs/default.json, then to
#                      42 only if neither file exists.
#   OUTPUT_ROOT        root under which exp_<name>/ trees are created.
#                      Default 'results' produces the layout above.
#
# Generated by scripts/regenerate_experiment_scripts.py.
# =============================================================================

set -euo pipefail

# ── Locate repo + source _config.sh (cluster+personal settings) ─────
if [ -n "${SLURM_SUBMIT_DIR:-}" ]; then
    UCI_DIR="$SLURM_SUBMIT_DIR/scripts/slurm/uci-hpc3"
else
    # _array_common.sh is at .../uci-hpc3/array/, _config.sh at .../uci-hpc3/
    UCI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
fi
# shellcheck source=../_config.sh
source "$UCI_DIR/_config.sh"

# ── Repo + venv + modules ───────────────────────────────────────────
cd "$CORDIS_REPO_DIR"
mkdir -p logs/slurm

module purge
module load "$CORDIS_PYTHON_MODULE"
# shellcheck source=/dev/null
source "$CORDIS_VENV/bin/activate"

# ── Compute per-task trial count, seed, run-id ──────────────────────
# N_ARRAY_TASKS defaults to whatever SLURM allocated (always available
# inside an array job; falls back to 1 if user invoked the script
# outside SLURM for local debugging).
: "${N_ARRAY_TASKS:=${SLURM_ARRAY_TASK_COUNT:-1}}"
: "${ARRAY_TASK_ID:=${SLURM_ARRAY_TASK_ID:-0}}"
: "${ARRAY_JOB_ID:=${SLURM_ARRAY_JOB_ID:-local}}"

# BASE_SEED — read from cfg.simulation.seed when not explicitly set, so
# the JSON config remains the single source of truth.  Explicit env-var
# override still wins for ad-hoc submissions:
#     BASE_SEED=99 sbatch scripts/slurm/uci-hpc3/array/exp_<name>.array.sub
if [ -z "${BASE_SEED:-}" ]; then
    _CFG="configs/exp_${EXP_NAME}.json"
    [ ! -f "$_CFG" ] && _CFG="configs/default.json"
    if [ -f "$_CFG" ]; then
        BASE_SEED=$(python3 -c             "import json; cfg=json.load(open('$_CFG'));              print(cfg.get('simulation',{}).get('seed',42))")
    else
        # Last-resort fallback if no config file is present at all.
        BASE_SEED=42
    fi
fi

# N_TRIALS_TOTAL — the total Monte-Carlo count across the whole array
# — is the same quantity as cfg.simulation.n_trials, so read it from
# the config to keep the JSON file as the single source of truth.
# Explicit env-var override still wins for ad-hoc submissions:
#     N_TRIALS_TOTAL=2000 sbatch scripts/slurm/uci-hpc3/array/exp_<name>.array.sub
if [ -z "${N_TRIALS_TOTAL:-}" ]; then
    _CFG="configs/exp_${EXP_NAME}.json"
    [ ! -f "$_CFG" ] && _CFG="configs/default.json"
    if [ -f "$_CFG" ]; then
        N_TRIALS_TOTAL=$(python3 -c             "import json; cfg=json.load(open('$_CFG'));              print(cfg.get('simulation',{}).get('n_trials',500))")
    else
        # Last-resort fallback if no config file is present at all.
        N_TRIALS_TOTAL=500
    fi
fi

# Ceiling division so the final task picks up the remainder when
# N_TRIALS_TOTAL is not divisible by N_ARRAY_TASKS.  Last task may
# do slightly fewer trials than its share; that's fine.
export N_TRIALS=$(( (N_TRIALS_TOTAL + N_ARRAY_TASKS - 1) / N_ARRAY_TASKS ))
# Each task uses a unique base seed; SeedSequence(SEED).spawn(...) is
# prefix-stable so different SEED values yield disjoint streams.
export SEED=$(( BASE_SEED + ARRAY_TASK_ID ))
# RUN_ID becomes the leaf directory name under results/exp_<name>/,
# replacing the auto-timestamp.  Predictable, unique per task,
# trivially globbed by the aggregator.
export RUN_ID="array_${ARRAY_JOB_ID}_task_${ARRAY_TASK_ID}"
# OUTPUT_ROOT stays at 'results' — the runner appends exp_<name>/
# automatically.  Resulting path:
#   results/exp_<name>/array_<jobid>_task_<id>/
export OUTPUT_ROOT="${OUTPUT_ROOT:-results}"

# Worker count tracks the SLURM allocation (40 by default on HPC3).
export N_WORKERS="${SLURM_CPUS_PER_TASK:-1}"

# Ensure cordis is importable without `pip install -e .`.
export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

# Tag for log messages identifying this run inside per-task logs.
export TAG="array_${ARRAY_JOB_ID}_t${ARRAY_TASK_ID}"
